dataSources:
  # 定义数据源，这里使用一个默认的数据源
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/shortlink?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1019fxmm

rules:
  - !SHARDING
    # 配置t_user表的分片规则
    tables:
      t_user:
        # 实际数据节点，表示t_user表的数据分布在ds_0.t_user_0到ds_0.t_user_15这16张表中
        actualDataNodes: ds_0.t_user_${0..15}

        # 分表策略
        tableStrategy:
          standard:
            # 分片键，这里使用username的hashcode进行分片
            shardingColumn: username
            # 分片算法，将数据路由到16张分表中
            shardingAlgorithmName: t_user_table_sharding_algorithm
      t_group:
        # 实际数据节点，表示t_user表的数据分布在ds_0.t_user_0到ds_0.t_user_15这16张表中
        actualDataNodes: ds_0.t_group_${0..15}

        # 分表策略
        tableStrategy:
          standard:
            # 分片键，这里使用username的hashcode进行分片
            shardingColumn: username
            # 分片算法，将数据路由到16张分表中
            shardingAlgorithmName: t_group_table_sharding_algorithm
    # 配置分片算法
    shardingAlgorithms:
      # t_user表的分表算法
      t_user_table_sharding_algorithm:
        type: HASH_MOD
        props:
          # 分片数量，对应16张表
          sharding-count: '16'
      t_group_table_sharding_algorithm:
        type: HASH_MOD
        props:
          # 分片数量，对应16张表
          sharding-count: '16'
  # 数据加密存储规则
  - !ENCRYPT
    # 需要加密的表集合
    tables:
      # 用户表
      t_user:
        # 用户表中哪些字段需要进行加密
        columns:
          # 手机号字段，逻辑字段，不一定是在数据库中真实存在
          phone:
            # 手机号字段存储的密文字段，这个是数据库中真实存在的字段
            cipherColumn: phone
            # 身份证字段加密算法
            encryptorName: common_encryptor
          mail:
            cipherColumn: mail
            encryptorName: common_encryptor
        # 是否按照密文字段查询
        queryWithCipherColumn: true
    # 加密算法
    encryptors:
      # 自定义加密算法名称
      common_encryptor:
        # 加密算法类型
        type: AES
        props:
          # AES 加密密钥
          aes-key-value: d6oadClrrb9A3GWo
props:
  # 是否在日志中打印SQL解析和改写信息
  sql-show: true
  # 是否在日志中打印简单SQL，默认为false
  sql-simple: false